version: '3.8'

services:
  tor:
    build: ./tor
    image: goldy/tor-hidden-service
    container_name: tor_service
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=tyler_durden
      - POSTGRES_PASSWORD=KJ#56e35thfg*!@#GG5
      - POSTGRES_DB=deep_web
    ports:
      - '5432:5432'
    volumes:
      - db_deep_web:/var/lib/postgresql/data
    depends_on:
      - tor
      
  web:
    build: ./web
    container_name: django_web
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web:/web
    ports:
      - '8000:8000'

    depends_on:
      - postgres
      - tor

volumes:
  db_deep_web:  
  web: